In [8]:
import pandas as pd

# extracting the raw data file
df = pd.read_csv('../../data/raw/boxing_matches_messy_data.csv')
df.head()

,age_A,age_B,height_A,height_B,reach_A,reach_B,stance_A,stance_B,weight_A,weight_B,...,kos_A,kos_B,result,decision,judge1_A,judge1_B,judge2_A,judge2_B,judge3_A,judge3_B
0,35.0,27.0,179.0,175.0,178.0,179.0,orthodox,orthodox,160.0,160.0,...,33.0,34.0,draw,NaN,110.0,118.0,115.0,113.0,114.0,114.0
1,26.0,31.0,173.0,185.0,179.0,185.0,orthodox,orthodox,164.0,164.0,...,34.0,32.0,win_A,UD,120.0,108.0,120.0,108.0,120.0,108.0
2,28.0,NaN,176.0,175.0,178.0,179.0,orthodox,orthodox,154.0,154.0,...,13.0,33.0,win_B,KO,58.0,54.0,57.0,54.0,58.0,54.0
3,25.0,29.0,175.0,174.0,178.0,180.0,orthodox,orthodox,NaN,155.0,...,32.0,NaN,win_A,KO,47.0,48.0,49.0,46.0,48.0,47.0
4,25.0,35.0,175.0,173.0,179.0,170.0,orthodox,orthodox,139.0,140.0,...,32.0,33.0,win_A,UD,118.0,110.0,119.0,109.0,117.0,111.0

In [9]:
df.tail()

,age_A,age_B,height_A,height_B,reach_A,reach_B,stance_A,stance_B,weight_A,weight_B,...,kos_A,kos_B,result,decision,judge1_A,judge1_B,judge2_A,judge2_B,judge3_A,judge3_B
418087,21.0,20.0,173.0,173.0,NaN,178.0,orthodox,orthodox,146.0,140.0,...,1.0,1.0,draw,PTS,58.0,54.0,57.0,54.0,58.0,54.0
418088,24.0,26.0,173.0,173.0,178.0,178.0,orthodox,orthodox,139.0,140.0,...,7.0,10.0,NaN,RTD,58.0,54.0,57.0,54.0,58.0,54.0
418089,24.0,26.0,173.0,NaN,-178.0,178.0,orthodox,orthodox,169.0,140.0,...,0.0,0.0,win_A,TKO,58.0,54.0,57.0,54.0,58.0,54.0
418090,33.0,19.0,173.0,173.0,178.0,178.0,southpaw,southpaw,139.0,140.0,...,1.0,0.0,draw,PTS,58.0,54.0,57.0,54.0,58.0,54.0
418091,24.0,22.0,192.0,188.0,194.0,178.0,orthodox,orthodox,139.0,140.0,...,10.0,2.0,win_A,UD,80.0,70.0,80.0,72.0,80.0,73.0

In [10]:
df.shape

(418092, 26)

In [11]:
df.isnull().sum()

age_A       20947
age_B       20955
height_A    20977
height_B    20982
reach_A     20974
reach_B     20971
stance_A    20112
stance_B    20006
weight_A    21001
weight_B    20935
won_A       20939
won_B       20919
lost_A      20934
lost_B      20909
drawn_A     20914
drawn_B     20965
kos_A       20946
kos_B       20979
result      20126
decision    20045
judge1_A    20956
judge1_B    21007
judge2_A    20940
judge2_B    20955
judge3_A    20931
judge3_B    20941
dtype: int64