In [8]:
"""
The data has already been processed however a last minute change in specifications has shown
that dates need to be added which was considered unnecessary at first.
"""

'\nThe data has already been processed however a last minute change in specifications has shown\nthat dates need to be added which was considered unnecessary at first.\n'

In [9]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

In [10]:
df = pd.read_csv('../data/processed/final_processed_data/boxing-match-fighters.csv')
df

,Unnamed: 0,Rating_A,Boxer_A,Country_A,Weight_A,age_A,height_A,reach_A,stance_A,weight_A,...,judge3_B,class_B,rank_B,Sex,Weight_Class,decision,class_diff,won_A.1,won_B.1,result
0,0,1.0,"Alvarez, Canelo",MX,76.203518,35.0,179.0,178.0,Orthodox,85.067857,...,114.0,Cruiserweight,16,Male,Cruiserweight,KO,0,37,49,draw
1,1,1.0,"Alvarez, Canelo",MX,76.203518,26.0,173.0,179.0,Orthodox,101.736004,...,108.0,Heavyweight,17,Male,Cruiserweight,UD,0,48,50,win_A
2,2,1.0,"Alvarez, Canelo",MX,76.203518,28.0,176.0,178.0,Orthodox,73.556933,...,54.0,Super Middleweight,14,Male,Cruiserweight,KO,0,23,47,win_B
3,3,1.0,"Alvarez, Canelo",MX,76.203518,25.0,175.0,178.0,Orthodox,70.045370,...,47.0,Middleweight,13,Male,Cruiserweight,KO,0,46,31,win_A
4,4,1.0,"Alvarez, Canelo",MX,76.203518,25.0,175.0,179.0,Orthodox,69.239917,...,111.0,Super Welterweight,12,Male,Cruiserweight,UD,0,45,40,win_A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331147,331147,1469.0,"Barrionuevo, Cesar",AR,72.574779,28.0,163.0,178.0,Orthodox,123.000000,...,54.0,Heavyweight,17,Male,Middleweight,PTS,0,31,8,draw
331148,331148,1469.0,"Barrionuevo, Cesar",AR,72.574779,28.0,163.0,178.0,Orthodox,120.000000,...,54.0,Heavyweight,17,Male,Middleweight,PTS,0,21,36,win_A
331149,331149,1469.0,"Barrionuevo, Cesar",AR,72.574779,27.0,163.0,178.0,Orthodox,116.000000,...,54.0,Heavyweight,17,Male,Middleweight,PTS,0,13,9,win_A
331150,331150,1469.0,"Barrionuevo, Cesar",AR,72.574779,27.0,163.0,178.0,Orthodox,69.790513,...,54.0,Middleweight,13,Male,Middleweight,RTD,1,69,5,win_A
331151,331151,1469.0,"Barrionuevo, Cesar",AR,72.574779,27.0,163.0,178.0,Orthodox,115.000000,...,54.0,Heavyweight,17,Male,Middleweight,PTS,0,68,4,win_A

In [11]:
start_date = datetime(2010, 1, 1)
end_date   = datetime(2025, 12, 31)

In [12]:
def generate_date_of_match(start, end): # start and end as it can start after 2010 and end in 2025
    delta = end - start
    random_days = np.random.randint(0, delta.days)
    return start + timedelta(days=int(random_days))

assigned_dates = {}

generated_dates = []

In [13]:
for idx, row in df.iterrows():
    fighterA = row["Boxer_A"]
    fighterB = row["Boxer_B"]
    
    fighter_key = tuple(sorted([fighterA, fighterB]))
    
    while True:
        d = generate_date_of_match(start_date, end_date).date()

        # Check if either fighter already has this date
        clash = False
        for f in [fighterA, fighterB]:
            if f in assigned_dates and d in assigned_dates[f]:
                clash = True
                break
        
        if not clash:
            # Assign to both fighters
            for f in [fighterA, fighterB]:
                assigned_dates.setdefault(f, set()).add(d)
            generated_dates.append(d)
            break

In [14]:
df["Fight_Date"] = generated_dates

In [18]:
df.to_csv("../data/processed/final_processed_data/boxing-match-fighters.csv", index=False)

In [19]:
df[['Boxer_A', 'Boxer_B', 'Fight_Date']].head()

           Boxer_A           Boxer_B  Fight_Date
0  Alvarez, Canelo  Beterbiev, Artur  2014-04-19
1  Alvarez, Canelo     Bivol, Dmitry  2019-05-30
2  Alvarez, Canelo   Briedis, Mairis  2017-07-25
3  Alvarez, Canelo  Benavidez, David  2023-10-09
4  Alvarez, Canelo   Berlanga, Edgar  2024-11-09